# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0779289a9ded575f71665e86cf3b74742f66c63bd4d871cc34d1a0410b2771a0a248d853bf8b60a15a9e8e28778ff548502e4aa3b26f6ca36ae51cbbb94398b

test:
  secret_key_base: 5ce0d883fc0572feab478329e76e7fae8eccdae3803e33a3d5cc19608bac99a5b23695c77f1ffecb5ac3ca1b6ae7c53eb7a9725a95a8a0aa95a7a18eeadca3f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
